# This YAML defines a ConfigMap named grafana-config
# that stores configuration for Grafana datasources.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasources.yml:
    apiVersion: 1

    # This section lists all the datasource configurations
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        jsonData:
          httpMethod: GET
          # This defines where exemplar trace IDs are sent
          exemplarTraceIdDestinations:
            - datasourceUid: tempo
              name: trace_id

      # Second datasource configuration for Loki
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        orgId: 1
        url: http://loki:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false

      # Third datasource configuration for Tempo (set as default)
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: http://tempo:3200
        basicAuth: false
        isDefault: true
        version: 1
        editable: false
        apiVersion: 1  
        uid: tempo
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus  # Datasource UID used for service mapping
          tracesToLogsV2:
            datasourceUid: loki        # Datasource UID used for storing logs
            spanStartTimeShift: '-1h'  # Time shift applied to trace span start time
            spanEndTimeShift: '1h'     # Time shift applied to trace span end time
            filterByTraceID: true       # Filter traces by trace ID
            filterBySpanID: true        # Filter traces by span ID
            tags:
              - key: 'service.name'     # Tag key for filtering
                value: 'job'           # Tag value for filtering
